name: GitVersion Demo
on: 
  - workflow_dispatch
  - push

jobs:
  demo:
    name: GitVersion Demonstration
    runs-on: ubuntu-latest
    outputs:
      outputtest: "${{ steps.determine-version.outputs.fullSemVer }}"
      
    steps:
    
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show Current Branch
        run: git branch --show-current
              
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
         versionSpec: '5.x'
            
      - name: Display GitVersion config
        uses: gittools/actions/gitversion/execute@v0
        with:
          additionalArguments: '/showConfig'
          
      - id: determine-version
        name: Determine Semantic Versions
        uses: gittools/actions/gitversion/execute@v0
              
      - name: Display GitVersion outputs
        run: |
          echo "Major: ${{ steps.determine-version.outputs.major }}" | tee version-output.txt
          echo "Minor: ${{ steps.determine-version.outputs.minor }}" | tee version-output.txt -a
          echo "Patch: ${{ steps.determine-version.outputs.patch }}" | tee version-output.txt -a
          echo "PreReleaseTag: ${{ steps.determine-version.outputs.preReleaseTag }}" | tee version-output.txt -a
          echo "PreReleaseTagWithDash: ${{ steps.determine-version.outputs.preReleaseTagWithDash }}" | tee version-output.txt -a
          echo "PreReleaseLabel: ${{ steps.determine-version.outputs.preReleaseLabel }}" | tee version-output.txt -a
          echo "PreReleaseNumber: ${{ steps.determine-version.outputs.preReleaseNumber }}" | tee version-output.txt -a
          echo "WeightedPreReleaseNumber: ${{ steps.determine-version.outputs.weightedPreReleaseNumber }}" | tee version-output.txt -a
          echo "BuildMetaData: ${{ steps.determine-version.outputs.buildMetaData }}" | tee version-output.txt -a
          echo "BuildMetaDataPadded: ${{ steps.determine-version.outputs.buildMetaDataPadded }}" | tee version-output.txt -a
          echo "FullBuildMetaData: ${{ steps.determine-version.outputs.fullBuildMetaData }}" | tee version-output.txt -a
          echo "MajorMinorPatch: ${{ steps.determine-version.outputs.majorMinorPatch }}" | tee version-output.txt -a
          echo "SemVer: ${{ steps.determine-version.outputs.semVer }}" | tee version-output.txt -a
          echo "LegacySemVer: ${{ steps.determine-version.outputs.legacySemVer }}" | tee version-output.txt -a
          echo "LegacySemVerPadded: ${{ steps.determine-version.outputs.legacySemVerPadded }}" | tee version-output.txt -a
          echo "AssemblySemVer: ${{ steps.determine-version.outputs.assemblySemVer }}" | tee version-output.txt -a
          echo "AssemblySemFileVer: ${{ steps.determine-version.outputs.assemblySemFileVer }}" | tee version-output.txt -a
          echo "FullSemVer: ${{ steps.determine-version.outputs.fullSemVer }}" | tee version-output.txt -a
          echo "InformationalVersion: ${{ steps.determine-version.outputs.informationalVersion }}" | tee version-output.txt -a
          echo "BranchName: ${{ steps.determine-version.outputs.branchName }}" | tee version-output.txt -a
          echo "EscapedBranchName: ${{ steps.determine-version.outputs.escapedBranchName }}" | tee version-output.txt -a
          echo "Sha: ${{ steps.determine-version.outputs.sha }}" | tee version-output.txt -a
          echo "ShortSha: ${{ steps.determine-version.outputs.shortSha }}" | tee version-output.txt -a
          echo "NuGetVersionV2: ${{ steps.determine-version.outputs.nuGetVersionV2 }}" | tee version-output.txt -a
          echo "NuGetVersion: ${{ steps.determine-version.outputs.nuGetVersion }}" | tee version-output.txt -a
          echo "NuGetPreReleaseTagV2: ${{ steps.determine-version.outputs.nuGetPreReleaseTagV2 }}" | tee version-output.txt -a
          echo "NuGetPreReleaseTag: ${{ steps.determine-version.outputs.nuGetPreReleaseTag }}" | tee version-output.txt -a
          echo "VersionSourceSha: ${{ steps.determine-version.outputs.versionSourceSha }}" | tee version-output.txt -a
          echo "CommitsSinceVersionSource: ${{ steps.determine-version.outputs.commitsSinceVersionSource }}" | tee version-output.txt -a
          echo "CommitsSinceVersionSourcePadded: ${{ steps.determine-version.outputs.commitsSinceVersionSourcePadded }}" | tee version-output.txt -a
          echo "UncommittedChanges: ${{ steps.determine-version.outputs.uncommittedChanges }}" | tee version-output.txt -a
          echo "CommitDate: ${{ steps.determine-version.outputs.commitDate }}" | tee version-output.txt -a

      - name: Store the output artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: version-output.txt

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      - name: Restore Dependencies
        run: dotnet restore ./src

      - name: Build
        run: dotnet build ./src --no-restore

      - name: Test
        run: dotnet test ./src --no-restore --no-build

      - name: Pack
        run: dotnet pack ./src --no-restore

      - name: Show created packages
        run: find . -name "*.nupkg"

      - name: Show built dll versions
        shell: pwsh
        run: |
          (Get-ChildItem ./src/library/bin/*/*/library.dll).VersionInfo
          (Get-ChildItem ./src/app/bin/*/*/app.dll).VersionInfo
          (Get-ChildItem ./src/library.tests/bin/*/*/library.tests.dll).VersionInfo
  
      - name: Print some stuff
        run: |
          echo "Action: ${{ github.action }}"
          echo "Repo: ${{ github.action_repository }}"
          echo "Status: ${{ github.action_status }}"
          echo "Actor: ${{ github.actor }}"
          echo "Triggering Actor: ${{ github.triggering_actor }}"
          echo "Action: ${{ github.action.branch }}"
          echo "${{ github.event }}"
          echo "${{ github.event_name }}"
          echo "${{ github.event_path }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.workspace }}"
          echo "${{ github.workflow }}"
          echo "${{ github.path }}"
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"

      - name: Show created packages
        run: |
          echo ${{ steps.determine-version.conclusion }}
          echo ${{ steps.determine-version.outcome }}
